version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mura
      # MONGO_INITDB_ROOT_PASSWORD: purple
      # - MONGO_INITDB_ROOT_USERNAME=mura
    env_file:
      - ./env/mongo.env

  backend:
    build: ./backend
    container_name: backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: