version: '3.9'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile

    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    platform: linux/amd64
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    container_name: artisan
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/wwww/html/artisan"]

  npm:
    container_name: npm
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html